### ISSUE TITLE
Fix deployment on NOI's infrastructure

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/aliens4friends-dashboard#21]
It shows only Loading... on https://dashboard.solda.testingmachine.eu/

- It might be an issue with the nginx docker?
- I will post some logs here asap

This blocks #8

**Comment by Piiit** [comment]
@mrabans I do not know if this helps but we get a lot of these messages

```
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34418 Accepted
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34418 Closing
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34426 Accepted
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34426 Closing
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34430 Accepted
app_1    | [Tue Sep 14 15:08:25 2021] 34.255.139.75:34430 Closing
```

**Comment by mrabans** [comment]
right, with #22 it should be resolved.

**Comment by Piiit** [comment]
@mrabans The problem is still there, could you please have a look... if you like we could also have a pair programming session with Alex C?

**Comment by Piiit** [comment]
Error in browser console is: `GET https://dashboard.solda.testingmachine.eu/js/app.js net::ERR_ABORTED 404 (Not Found)`

**Comment by mrabans** [comment]
try PR #23

**Comment by Piiit** [comment]
@mrabans Works, thanks!
